#-------------------------------
# General Site Settings

menu:
- {name: 'Classes', url: 'pages/posts'}
- {name: 'Syllabus', url: 'pages/syllabus'}
- {name: 'Contact', url: 'pages/contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Class website for Purchase College course Programming For Visual Artists, Fall 2020'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'namegoeshere'

#-------------------------------
# About Section

about: >
  # Programming For Visual Artists

  Programming for Visual Artists introduces code as a medium to create interactive visual art. We will explore the evolving history of new media and software art. You will be encouraged to push the edges of art into new and unknown territory. We will learn the basics of programming with the JavaScript library p5.js through in-class lectures, demonstrations and exercises. We will study a diverse community of artists and approaches, and we will take an expansive view of how programming can be used as a tool to create new forms of art. Outside of class, students will have weekly readings, video tutorials, writing prompts and programming assignments.

  Taught by [Lee Tusman](http://leetusman.com).

contact: >
  # Contact

  You may contact Lee through [email](mailto:lee.tusmanATpurchase.edu) if you have any questions or would like to bring up any issues.

#-------------------------------
# Work Section

projects:
# To list project pages, uncomment the following lines and add these files!
#- {name: 'Project One', folder: 'proj-1', file: 'projects/proj-1.html'}
#- {name: 'Project Two', folder: 'proj-2', file: 'projects/proj-2.html'}
#- {name: 'Project Three', folder: 'proj-3', file: 'projects/proj-3.html'}

#-------------------------------
# Contact Section

social:
#- {icon: 'twitter', link: '#'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
#
#
#-------------------------------
# Footer section

footer: >
  <a href="https://www.purchase.edu/academics/new-media" alt="Purchase College New Media Department">Purchase College New Media</a>
